sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install -g codecov
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script:
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHTOKEN
  local_dir: project/itlen.github.io