sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
script:
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHTOKEN
  local_dir: project/itlen.github.io