sudo: false
language:
  node_js
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHTOKEN
  local_dir: project/itlen.github.io